import { js, copyDirectory } from 'laravel-mix';

js('resources/assets/js/vendor/modernizr-3.5.0.min.js', 'public/js')
   .js('resources/assets/js/vendor/jquery-1.12.4.min.js', 'public/js')
   .js('resources/assets/js/popper.min.js', 'public/js')
   .js('resources/assets/js/bootstrap.min.js', 'public/js')
   .js('resources/assets/js/jquery.slicknav.min.js', 'public/js')
   .js('resources/assets/js/owl.carousel.min.js', 'public/js')
   .js('resources/assets/js/slick.min.js', 'public/js')
   .js('resources/assets/js/gijgo.min.js', 'public/js')
   .js('resources/assets/js/wow.min.js', 'public/js')
   .js('resources/assets/js/animated.headline.js', 'public/js')
   .js('resources/assets/js/jquery.magnific-popup.js', 'public/js')
   .js('resources/assets/js/jquery.ticker.js', 'public/js')
   .js('resources/assets/js/site.js', 'public/js')
   .js('resources/assets/js/jquery.scrollUp.min.js', 'public/js')
   .js('resources/assets/js/jquery.nice-select.min.js', 'public/js')
   .js('resources/assets/js/jquery.sticky.js', 'public/js')
   .js('resources/assets/js/contact.js', 'public/js')
   .js('resources/assets/js/jquery.form.js', 'public/js')
   .js('resources/assets/js/jquery.validate.min.js', 'public/js')
   .js('resources/assets/js/mail-script.js', 'public/js')
   .js('resources/assets/js/jquery.ajaxchimp.min.js', 'public/js')
   .sass('resources/assets/css/bootstrap.min.css', 'public/css')
   .sass('resources/assets/css/owl.carousel.min.css', 'public/css')
   .sass('resources/assets/css/ticker-style.css', 'public/css')
   .sass('resources/assets/css/flaticon.css', 'public/css')
   .sass('resources/assets/css/slicknav.css', 'public/css')
   .sass('resources/assets/css/animate.min.css', 'public/css')
   .sass('resources/assets/css/magnific-popup.css', 'public/css')
   .sass('resources/assets/css/fontawesome-all.min.css', 'public/css')
   .sass('resources/assets/css/themify-icons.css', 'public/css')
   .sass('resources/assets/css/slick.css', 'public/css')
   .sass('resources/assets/css/nice-select.css', 'public/css')
   .sass('resources/assets/css/style.css', 'public/css')
   .version();

copyDirectory('resources/assets/img', 'public/images');
